### ISSUE TITLE
Android-Specific Error Encountered in Passkey Registration Process

### ISSUE THREAD

**Issue by yakirbitan** [f-23/react-native-passkey#29] opened 2024-01-22 20:34 UTC
Hello,

I'm currently integrating this library into my React Native application to enable passkey functionality. I have followed all the configuration steps outlined in the README.md, including setting up the associated domain and other relevant settings.

The implementation works flawlessly on iOS (version 17.2), where the passkey creation and usage are functioning as expected. However, I am encountering a problem on the Android platform. Despite a successful build and the appearance of the passkey creation popup on Android, an error occurs during the registration process. The error message is as follows:
```json
{
  "error": "Native error",
  "message": "androidx.credentials.exception.CreateCredentialCustomException:"
}
```

This issue is puzzling, as it seems to be specific to the Android environment, and I'm unsure of the underlying cause. I would greatly appreciate any insights or suggestions on what might be leading to this error. Could there be a step I'm missing, or is it potentially a bug within the library when used on Android?

Thank you in advance for your assistance and guidance. 🙏

**Comment by f-23** [comment] 2024-01-23 10:53
Hi @yakirbitan, 

Thank you for reporting this! I don't recall ever encountering this error during development, so I'm happy to look into it for you.
I just need some further clarification:
- What Android version are you using?
- Can you give me an example passkey request that triggers this error?
- Please double check if you've set up Digital Asset Links correctly!

**Comment by yakirbitan** [comment] 2024-01-23 13:33
> Hi @yakirbitan,
> 
> Thank you for reporting this! I don't recall ever encountering this error during development, so I'm happy to look into it for you. I just need some further clarification:
> 
> * What Android version are you using?
> * Can you give me an example passkey request that triggers this error?
> * Please double check if you've set up Digital Asset Links correctly!

@f-23 Thanks for your motivation to help 🙏

**Android Version**: 14
**Device**: Pixel 7 API 34
**Model**: sdk_gphone64_arm64

**Passkey Request**:
```json
{
  "attestation": null,
  "authenticatorSelection": {
    "requireResidentKey": false,
    "residentKey": "discouraged",
    "userVerification": "preferred"
  },
  "challenge": "kpPEPXgP7D1wjV6MlRBPSUz+nCtJisjOD+vywQMJkL8=",
  "excludeCredentials": [],
  "extensions": {
    "credProps": true
  },
  "pubKeyCredParams": [
    {
      "alg": -7,
      "type": "public-key"
    },
    {
      "alg": -257,
      "type": "public-key"
    }
  ],
  "rp": {
    "id": "localhost",
    "name": "Rewire"
  },
  "timeout": 1800000,
  "user": {
    "displayName": "Passkey Test",
    "id": "2HzoHm_hY0CjuEESY9tY6-3SdjmNHOoNqaPDcZGzsr0",
    "name": "Passkey Test"
  }
}
```

I double-checked everything in the Digital Asset Links in Android:
```
  GET https://<mydomain>/.well-known/assetlinks.json
  ```
```json
[
  {
    "relation": [
      "delegate_permission/common.handle_all_urls",
      "delegate_permission/common.get_login_creds"
    ],
    "target": {
      "namespace": "android_app",
      "package_name": "com.rewire.app",
      "sha256_cert_fingerprints": [
        SHA_HEX_VALUE // this was replaced with the real SHA_HEX_VALUE
      ]
    }
  }
]
```

Moreover, this is the popup:
![image](https://github.com/f-23/react-native-passkey/assets/79873428/ba450eb1-4b41-48bf-aea2-6953e741c204)

The error came from line 34 ([link](https://github.com/f-23/react-native-passkey/blob/stable/android/src/main/java/com/reactnativepasskey/PasskeyModule.kt)):
```java
val result = currentActivity?.let { credentialManager.createCredential(it, createPublicKeyCredentialRequest) }
```

This is the information I got from the debugger with Android Studio:
![image](https://github.com/f-23/react-native-passkey/assets/79873428/bab1b4eb-7fe3-4696-bb42-3fdfbc78bfb0)

It shows that there is an error related to Google Password Manager but without an explanation of what causes it.

**Comment by yakirbitan** [comment] 2024-01-27 09:54
@f-23,

I appreciate your willingness to help with the issue I've encountered. To facilitate a more detailed investigation, I've created a simplified React Native project that replicates the issue using your library. Unfortunately, the same error persists, hindering the passkey functionality on Android devices. The project is available at: https://github.com/yakirbitan/passkey

Error encountered:
```json
{
  "error": "Native error",
  "message": "androidx.credentials.exception.CreateCredentialCustomException:"
}
```

I have verified the assetlinks.json configuration thoroughly, ensuring it aligns with the expected setup. The verification command outputs confirm that the digital asset links are correctly associated:

```yaml
Copy code
➜ passkey git:(main) adb shell pm get-app-links com.google.credentialmanager.sample
com.google.credentialmanager.sample:
  ID: 1def815a-7fb5-4d00-8098-c20220144ef3
  Signatures: [FA:C6:17:45:DC:09:03:78:6F:B9:ED:E6:2A:96:2B:39:9F:73:48:F0:BB:6F:89:9B:83:32:66:75:91:03:3B:9C]
  Domain verification state:
    www.glitch.me: 1024
    passkeys-codelab.glitch.me: 1024
```
Additional details for your reference:

1. React Native version: v18.19.0
2. NPM version: v10.2.3
3. Note: Java home might need to be configured to match your system. Example path: "org.gradle.java.home=/Users/yakirbitan/Library/Java/JavaVirtualMachines/corretto-17.0.9/Contents/Home"

I conducted a test on an Android platform without React Native. I "implemented" a passkey feature using a different repository recommended in the Android documentation (https://github.com/android/identity-samples/tree/main/CredentialManager). This implementation was successful on the same device and with the same assetlinks.json configuration, suggesting the issue may lie within your library.

I'm eager to resolve this as quickly as possible and would greatly appreciate any further insights or suggestions you might have. Could there be a specific aspect of the library's integration with Android that I'm overlooking, or might there be an underlying issue within the library itself?

Thank you for your continued support and guidance.

**Comment by f-23** [comment] 2024-01-29 20:41
@yakirbitan Thank you! Unfortunately I'm having a hard time fully reproducing your setup on my end, so I wasn't able to reproduce this issue either.

On another note, is there a reason why your request contains `attestation: null` instead of `attestation: 'none'`?

**Comment by ManuGowda** [comment] 2024-02-09 08:58
> @yakirbitan Thank you! Unfortunately I'm having a hard time fully reproducing your setup on my end, so I wasn't able to reproduce this issue either.
> 
> On another note, is there a reason why your request contains `attestation: null` instead of `attestation: 'none'`?

@f-23 we are also facing the exact same issue.

We also tried to apply your suggestion `attestation: null instead of attestation: 'none'` but it resulted in same error.

**Comment by r-n-o** [comment] 2024-02-12 20:30
@f-23 also running into this error and I made some progress: I tracked it down to be (in my case at least) caused by a "bad" userId field: **Android requires this to be a valid base64-encoded string** (like you have [here](https://github.com/f-23/react-native-passkey/blob/17184a1b1f6f3ac61e07aa784c9b64efb28b570e/src/__tests__/testData/RegRequest.json#L8) for example). The error I was getting before (same error as the one posted by OP):
```
{
  "error": "Native error",
  "message": "androidx.credentials.exception.CreateCredentialCustomException:"
}
```

I looked at Android debug logs with Android Studio and spotted the following line:
```
[CreateRemotePasskeyOperation] Operation failed. [CONTEXT service_id=68 ] eibg: java.lang.IllegalArgumentException: bad base-64
```

I fixed this with https://github.com/r-n-o/passkeyapp/commit/ff75582460ff0662f99dcc462ba8169c229e512c. Now I'm getting a different error when creating passkeys:
```
[Error: private key must be 32 bytes, hex or bigint, not undefined]
```
<details>
<summary>Click to see the full log from Android Studio</summary>
<pre>
14:21:28.043  I  [RegistrationRequestHandler] Registering Discoverable Credential
14:21:28.043  I  [AuthenticateChimeraActivity] Flow to background [CONTEXT service_id=287 ]
14:21:28.151  E  Failed to find provider info for subscribedfeeds
14:21:28.151  E  Failed to find provider info for subscribedfeeds
14:21:28.179  I  [Fido2RequestController] Inside RegistrationOperation.Callback#onRegistrationResult. response: AuthenticatorAttestationResponse{keyHandle=5EF4764B099D3345A7971969AD31A6C1, clientDataJSON=7B2274797065223A22776562617574686E2E637265617465222C226368616C6C656E6765223A226E686B5158664535394A6239375679794E4A6B7644695875634D45766C746475766372446D47724F444859222C226F726967696E223A22616E64726F69643A61706B2D6B65792D686173683A513669443672576479514F5A7A77426546774555445877695A434B614E446C425F5051365F4F456B413045222C22616E64726F69645061636B6167654E616D65223A2278797A2E746B68716C6162732E706173736B6579617070227D, attestationObject=A363666D74646E6F6E656761747453746D74A068617574684461746158945E602CEDC7BE56AD17170C518E1A1955544EB3BF6FDE132393A099CD1A7F38295D00000000EA9B8D664D011D213CE4B6B48CB575D400105EF4764B099D3345A7971969AD31A6C1A50102032620012158209BFA8791517BB8C05B6CDCDF36F582B45601C2CF56460BF981DBBAE85A952B3122582014D78020BDEBAB0A8A7A5A72350504393FAC8DD88FAF406AD82435AF6D8CE252, transports=[internal, cable]}, type: screen_lock, didCreateDiscoverableCredential: true, unsignedOutputs: UnsignedOutputs{dpk=Optional.of(com.google.android.gms.fido.fido2.api.common.AuthenticationExtensionsDevicePublicKeyOutputs@3c1), prf=Optional.absent()}
14:21:28.180  I  [Fido2ApiImpl] Inside Fido2RequestController.Callback#onSecurityKeyResultReceived. response: AuthenticatorAttestationResponse{keyHandle=5EF4764B099D3345A7971969AD31A6C1, clientDataJSON=7B2274797065223A22776562617574686E2E637265617465222C226368616C6C656E6765223A226E686B5158664535394A6239375679794E4A6B7644695875634D45766C746475766372446D47724F444859222C226F726967696E223A22616E64726F69643A61706B2D6B65792D686173683A513669443672576479514F5A7A77426546774555445877695A434B614E446C425F5051365F4F456B413045222C22616E64726F69645061636B6167654E616D65223A2278797A2E746B68716C6162732E706173736B6579617070227D, attestationObject=A363666D74646E6F6E656761747453746D74A068617574684461746158945E602CEDC7BE56AD17170C518E1A1955544EB3BF6FDE132393A099CD1A7F38295D00000000EA9B8D664D011D213CE4B6B48CB575D400105EF4764B099D3345A7971969AD31A6C1A50102032620012158209BFA8791517BB8C05B6CDCDF36F582B45601C2CF56460BF981DBBAE85A952B3122582014D78020BDEBAB0A8A7A5A72350504393FAC8DD88FAF406AD82435AF6D8CE252, transports=[internal, cable]}, type: screen_lock, didCreateDiscoverableCredential: true, unsignedOutputs: UnsignedOutputs{dpk=Optional.of(com.google.android.gms.fido.fido2.api.common.AuthenticationExtensionsDevicePublicKeyOutputs@3c1), prf=Optional.absent()}, userPermissionForAllowList: false
14:21:28.180  I  [RequestController] Timeout Runnable is removed, and timer is stopped.
14:21:28.186  I  [RequestController] Timeout Runnable is removed, and timer is stopped.
14:21:28.186  I  [FidoApiImpl] updateTransaction is called for pause
14:21:28.186  E  [FidoApiImpl] pauseSecurityKeyRequestController should not be called when SecurityKeyRequestController is null.
14:21:28.211  E  'error during passkey creation', [Error: private key must be 32 bytes, hex or bigint, not undefined]
14:21:28.214  E  console.error: error during passkey creation Error: private key must be 32 bytes, hex or bigint, not undefined, js engine: hermes, stack:
                 _construct@1:106548
                 Wrapper@1:106202
                 _callSuper@1:104191
                 SyntheticError@1:105679
                 reactConsoleErrorHandler@1:105340
                 ?anon_0_@1:667898
                 asyncGeneratorStep@1:86463
                 _throw@1:86765
                 tryCallOne@53:15
                 anonymous@139:26
                 anonymous@1:259314
                 _callTimer@1:258313
                 _callReactNativeMicrotasksPass@1:258457
                 callReactNativeMicrotasks@1:260386
                 __callReactNativeMicrotasks@1:101731
                 anonymous@1:100867
                 __guard@1:101605
                 flushedQueue@1:100778
                 invokeCallbackAndReturnFlushedQueue@1:100721
</pre>
</details>

I think that's progress, it's a different error! 🎉

**Comment by r-n-o** [comment] 2024-02-12 20:52
Notes which may help future readers of this thread:
* If you are using Expo, make sure to configure expo to build an APK **and sign it with a debug keystore** (see [this](https://coderwall.com/p/r09hoq/android-generate-release-debug-keystores) on how to create a debug keystore):
  ```
  "android":  {
    "buildType": "apk",
    "credentialsSource": "local"
  }
  ```
* If you are testing on a simulator you need to log into a Google account on the simulator and configure PIN encryption to test passkey functionality. A good test to see if your simulator is set up correctly: visit webauthn.io from the Chrome browser and try to sign up / sign in with a passkey before testing your APK
* If you are testing on a real device, enable [developer mode](https://developer.android.com/studio/debug/dev-options) and pair your device with Android Studio (see [this](https://developer.android.com/studio/run/device#wireless)) to get debug logs via [LogCat](https://developer.android.com/studio/debug/logcat). That's really helpful to figure out what's going on.

**Comment by ManuGowda** [comment] 2024-02-14 09:24
> @f-23 also running into this error and I made some progress: I tracked it down to be (in my case at least) caused by a "bad" userId field: **Android requires this to be a valid base64-encoded string** (like you have [here](https://github.com/f-23/react-native-passkey/blob/17184a1b1f6f3ac61e07aa784c9b64efb28b570e/src/__tests__/testData/RegRequest.json#L8) for example). The error I was getting before (same error as the one posted by OP):
> 
> ```
> {
>   "error": "Native error",
>   "message": "androidx.credentials.exception.CreateCredentialCustomException:"
> }
> ```
> 
> I looked at Android debug logs with Android Studio and spotted the following line:
> 
> ```
> [CreateRemotePasskeyOperation] Operation failed. [CONTEXT service_id=68 ] eibg: java.lang.IllegalArgumentException: bad base-64
> ```
> 
> I fixed this with [r-n-o/passkeyapp@ff75582](https://github.com/r-n-o/passkeyapp/commit/ff75582460ff0662f99dcc462ba8169c229e512c). Now it's working and I can create passkeys just fine! 🎉 🎉 🎉

Great work @r-n-o 

Your fix helped us to resolve our issue and now its working on Android 🙏🏼

**Comment by armeo** [comment] 2024-04-26 10:54
And
```
"androidx.credentials:credentials-play-services-auth:1.2.2"
"androidx.credentials:credentials:1.2.2"
```
updated androidx credentials version, it's fixed for me.

**Comment by sirkostya009** [comment] 2024-06-28 11:25
May I also add that CredentialManager actually expects a base64url encoding on fields like challenge. You can see it [in the docs](https://developer.android.com/identity/sign-in/credential-manager#format-json-request).

**Comment by f-23** [comment] 2024-08-04 20:23
This should be fixed in version 3. It also includes improved error logging which could potentially make it easier to track down issues like this in the future.

**Closed by f-23** 2024-08-04 20:23 UTC
Labels: question, Android

**Comment by vikasvk3510** [comment] 2024-11-04 06:06
{"error": "Native error", "message": "androidx.credentials.exceptions.domerrors.SecurityError@7040a2d"}
